### ISSUE TITLE
chat emoji support

### ISSUE THREAD

**Issue by cgsdev0** [cgsdev0/rollycubes#63]

**Comment by brimonk** [comment]
As of writing, it looks like chat has emoji support. Should this still be open?
![image](https://user-images.githubusercontent.com/13184567/234755484-30e6d53e-d191-40d9-a447-7ebd6077275d.png)

**Comment by cgsdev0** [comment]
@brimonk added a better description; this is to add UI for picking emojis

**Comment by cgsdev0** [comment]
something like this:
```css
form button {
    width: 32px;
    height: 32px;
    position: absolute;
    right: 74px;
    bottom: 77px;
    border-radius: 64px;
}
form button::before {
    content: '😀';
}
```
